reducer_config:
    shape_reducer_optics:
        shape: rotateRectangle
        min_cluster_size: 2
        min_samples: 2
        cluster_selection_epsilon: 0.1
        allow_single_cluster: True
        metric_type: IoU
